/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAutomationRegistrar } from "./MockAutomationRegistrar";
export type { MockLINK } from "./MockLINK";
