const logo = "../../hexbox_name_logo_black.svg";
export const DUMMY_PROJECTS = [
  {
    _id: "1",
    user_id: "user1",
    title: "Project Alpha",
    description: "Description for Project Alpha",
    fund_amount: 10000.0,
    logo: `${logo}`,
    background_image: "background_alpha.png",
    hexbox_address: "solana_address_alpha",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
  {
    _id: "2",
    user_id: "user2",
    title: "Project Beta",
    description: "Description for Project Beta",
    fund_amount: 20000.0,
    logo: `${logo}`,
    background_image: "background_beta.png",
    hexbox_address: "solana_address_beta",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
  {
    _id: "3",
    user_id: "user3",
    title: "Project Gamma",
    description: "Description for Project Gamma",
    fund_amount: 300.5,
    logo: `${logo}`,
    background_image: "background_gamma.png",
    hexbox_address: "solana_address_gamma",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
  {
    _id: "4",
    user_id: "user4",
    title: "Project Delta",
    description: "Description for Project Delta",
    fund_amount: 400.7,
    logo: `${logo}`,
    background_image: "background_delta.png",
    hexbox_address: "solana_address_delta",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
  {
    _id: "5",
    user_id: "user5",
    title: "Project Epsilon",
    description: "Description for Project Epsilon",
    fund_amount: 2000.8,
    logo: `${logo}`,
    background_image: "background_epsilon.png",
    hexbox_address: "solana_address_epsilon",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
  {
    _id: "6",
    user_id: "user6",
    title: "Project Zeta",
    description: "Description for Project Zeta",
    fund_amount: 5000.7,
    logo: `${logo}`,
    background_image: "background_zeta.png",
    hexbox_address: "solana_address_zeta",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
  {
    _id: "7",
    user_id: "user7",
    title: "Project Eta",
    description: "Description for Project Eta",
    fund_amount: 70000.0,
    logo: `${logo}`,
    background_image: "background_eta.png",
    hexbox_address: "solana_address_eta",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
  {
    _id: "8",
    user_id: "user8",
    title: "Project Theta",
    description: "Description for Project Theta",
    fund_amount: 80000.0,
    logo: `${logo}`,
    background_image: "background_theta.png",
    hexbox_address: "solana_address_theta",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
  {
    _id: "9",
    user_id: "user9",
    title: "Project Iota",
    description: "Description for Project Iota",
    fund_amount: 90000.0,
    logo: `${logo}`,
    background_image: "background_iota.png",
    hexbox_address: "solana_address_iota",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
  {
    _id: "10",
    user_id: "user10",
    title: "Project Kappa",
    description: "Description for Project Kappa",
    fund_amount: 100000.0,
    logo: `${logo}`,
    background_image: "background_kappa.png",
    hexbox_address: "solana_address_kappa",
    created_at: "2024-10-24T00:00:00Z",
    status: true,
  },
];
