/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAutomationRegistrar } from "./IAutomationRegistrar";
export type { IAutomationRegistry } from "./IAutomationRegistry";
