/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAutomationRegistrar,
  IAutomationRegistrarInterface,
} from "../../../contracts/interfaces/IAutomationRegistrar";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onTokenTransfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "encryptedEmail",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "upkeepContract",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "gasLimit",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "adminAddress",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "triggerType",
        type: "uint8",
      },
      {
        internalType: "bytes",
        name: "checkData",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "triggerConfig",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "offchainConfig",
        type: "bytes",
      },
      {
        internalType: "uint96",
        name: "amount",
        type: "uint96",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAutomationRegistrar__factory {
  static readonly abi = _abi;
  static createInterface(): IAutomationRegistrarInterface {
    return new Interface(_abi) as IAutomationRegistrarInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAutomationRegistrar {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAutomationRegistrar;
  }
}
