/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAutomationRegistrar__factory } from "./IAutomationRegistrar__factory";
export { IAutomationRegistry__factory } from "./IAutomationRegistry__factory";
